name: Integrate

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: macOS-14
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.4.app/Contents/Developer
    strategy:
      matrix:
        destination:
          - "platform=macOS"
          - "platform=iOS Simulator,name=iPhone 15"

    steps:
      - uses: actions/checkout@v4
      - name: Get Scheme Names
        run: xcodebuild -list
      - name: Test platform ${{ matrix.destination }}
        run: set -o pipefail && xcodebuild -scheme DiscriminatedUnion -destination "${{ matrix.destination }}" -disableAutomaticPackageResolution test | xcbeautify
